"""Pure safety and mock-only policy contracts for recommendation stages."""

from ai_stock.recommendation.explanation_ui_preflight import (
    FORBIDDEN_EXPLANATION_SECTIONS,
    SAFE_EXPLANATION_SECTIONS,
    RecommendationExplanationSection,
    RecommendationExplanationSectionName,
    RecommendationExplanationUIPreflightPolicy,
    RecommendationExplanationValidationResult,
    RecommendationExplanationViewModel,
    build_default_recommendation_explanation_ui_policy,
    build_recommendation_explanation_view_model,
    validate_recommendation_explanation_ui_policy,
    validate_recommendation_explanation_view_model,
)
from ai_stock.recommendation.mock_policy_model import (
    ALLOWED_MOCK_LABELS,
    FORBIDDEN_MOCK_LABELS,
    MockRecommendationInput,
    MockRecommendationLabel,
    MockRecommendationPolicy,
    MockRecommendationResult,
    MockRecommendationValidationResult,
    build_default_mock_recommendation_policy,
    build_mock_recommendation_result,
    validate_mock_recommendation_input,
    validate_mock_recommendation_policy,
    validate_mock_recommendation_result,
)

from ai_stock.recommendation.safety_preflight import (
    ALLOWED_EXPLANATION_LANGUAGE,
    FORBIDDEN_RECOMMENDATION_LANGUAGE,
    REQUIRED_DISCLAIMERS,
    MockOnlyRecommendationPlan,
    RecommendationSafetyPreflightPolicy,
    RecommendationSafetyPreflightResult,
    build_default_recommendation_safety_preflight_policy,
    summarize_recommendation_safety_preflight,
    validate_recommendation_safety_preflight_policy,
)

__all__ = [
    "ALLOWED_EXPLANATION_LANGUAGE",
    "ALLOWED_MOCK_LABELS",
    "FORBIDDEN_EXPLANATION_SECTIONS",
    "FORBIDDEN_MOCK_LABELS",
    "FORBIDDEN_RECOMMENDATION_LANGUAGE",
    "REQUIRED_DISCLAIMERS",
    "SAFE_EXPLANATION_SECTIONS",
    "MockRecommendationInput",
    "MockRecommendationLabel",
    "MockRecommendationPolicy",
    "MockRecommendationResult",
    "MockRecommendationValidationResult",
    "MockOnlyRecommendationPlan",
    "RecommendationExplanationSection",
    "RecommendationExplanationSectionName",
    "RecommendationExplanationUIPreflightPolicy",
    "RecommendationExplanationValidationResult",
    "RecommendationExplanationViewModel",
    "RecommendationSafetyPreflightPolicy",
    "RecommendationSafetyPreflightResult",
    "build_default_mock_recommendation_policy",
    "build_default_recommendation_explanation_ui_policy",
    "build_default_recommendation_safety_preflight_policy",
    "build_mock_recommendation_result",
    "build_recommendation_explanation_view_model",
    "summarize_recommendation_safety_preflight",
    "validate_mock_recommendation_input",
    "validate_mock_recommendation_policy",
    "validate_mock_recommendation_result",
    "validate_recommendation_explanation_ui_policy",
    "validate_recommendation_explanation_view_model",
    "validate_recommendation_safety_preflight_policy",
]
