"""Toss API client foundation without live endpoint implementations."""

from ai_stock.clients.config import TossClientConfig
from ai_stock.clients.candles_smoke import (
    CANDLES_PATH,
    CandlesSmokeDiagnosticResult,
    CandlesSmokeResult,
    DEFAULT_CANDLE_ADJUSTED,
    DEFAULT_CANDLE_COUNT,
    DEFAULT_CANDLE_INTERVAL,
    DEFAULT_CANDLE_SYMBOL,
    TossCandlesSmokeClient,
)
from ai_stock.clients.exceptions import (
    TossApiError,
    TossAuthenticationError,
    TossClientConfigError,
    TossPermissionError,
    TossRateLimitError,
    TossServerError,
)
from ai_stock.clients.foundation import TossClientFoundation
from ai_stock.clients.market_data import TossMarketDataClient
from ai_stock.clients.market_info import TossMarketInfoClient
from ai_stock.clients.oauth import OAUTH_TOKEN_PATH, TossOAuthTokenProvider
from ai_stock.clients.prices_smoke import (
    DEFAULT_PRICE_SYMBOL,
    PRICES_PATH,
    PricesSmokeDiagnosticResult,
    PricesSmokeResult,
    TossPricesSmokeClient,
)
from ai_stock.clients.readonly_smoke import (
    EXCHANGE_RATE_PATH,
    ReadOnlySmokeResult,
    TossReadOnlySmokeClient,
)
from ai_stock.clients.request_context import (
    ACCOUNT_HEADER,
    AUTHORIZATION_HEADER,
    AuthenticatedRequestContext,
    AuthenticatedRequestContextFactory,
)
from ai_stock.clients.response import extract_toss_result, raise_for_toss_status
from ai_stock.clients.stock_info import TossStockInfoClient
from ai_stock.clients.stock_info_smoke import (
    DEFAULT_STOCK_SYMBOL,
    STOCKS_PATH,
    StockInfoSmokeDiagnosticResult,
    StockInfoSmokeResult,
    TossStockInfoSmokeClient,
)
from ai_stock.clients.stock_warnings_smoke import (
    DEFAULT_WARNING_SYMBOL,
    StockWarningsSmokeDiagnosticResult,
    StockWarningsSmokeResult,
    TossStockWarningsSmokeClient,
)
from ai_stock.clients.token_provider import LiveTokenProvider, MockTokenProvider, TokenProvider
from ai_stock.clients.token_store import InMemoryTokenStore
from ai_stock.clients.toss_api_client_contract import (
    TossApiClientContractPolicy,
    TossApiContractValidationResult,
    TossApiCredentialNamePolicy,
    TossApiEndpointContract,
    TossApiErrorContract,
    TossApiExternalCapabilityFlags,
    TossApiRedactionPolicy,
    TossApiRedactionResult,
    TossApiRequestContract,
    TossApiResponseContract,
    build_symbolic_toss_api_endpoint_contracts,
    build_toss_api_client_contract_policy,
    build_toss_api_credential_name_policy,
    build_toss_api_error_contracts,
    build_toss_api_external_capability_flags,
    build_toss_api_redaction_policy,
    build_toss_api_request_contract,
    build_toss_api_response_contract,
    redact_mapping,
    redact_sensitive_value,
    run_toss_api_client_contract_preflight_checks,
    validate_no_sensitive_output,
    validate_toss_api_client_contract_policy,
    validate_toss_api_endpoint_contract,
    validate_toss_api_request_contract,
    validate_toss_api_response_contract,
)
from ai_stock.clients.toss_api_fake_transport import (
    TossApiFakeFixture,
    TossApiFakeRequest,
    TossApiFakeResponse,
    TossApiFakeTransportPolicy,
    TossApiFakeTransportResult,
    TossApiFakeTransportValidationResult,
    build_toss_api_fake_fixtures,
    build_toss_api_fake_request,
    build_toss_api_fake_transport_policy,
    run_toss_api_fake_transport,
    run_toss_api_fake_transport_preflight_checks,
    validate_toss_api_fake_fixture,
    validate_toss_api_fake_transport_policy,
)

__all__ = [
    "ACCOUNT_HEADER",
    "AUTHORIZATION_HEADER",
    "AuthenticatedRequestContext",
    "AuthenticatedRequestContextFactory",
    "CANDLES_PATH",
    "CandlesSmokeDiagnosticResult",
    "CandlesSmokeResult",
    "DEFAULT_CANDLE_ADJUSTED",
    "DEFAULT_CANDLE_COUNT",
    "DEFAULT_CANDLE_INTERVAL",
    "DEFAULT_CANDLE_SYMBOL",
    "DEFAULT_PRICE_SYMBOL",
    "DEFAULT_STOCK_SYMBOL",
    "DEFAULT_WARNING_SYMBOL",
    "EXCHANGE_RATE_PATH",
    "InMemoryTokenStore",
    "LiveTokenProvider",
    "MockTokenProvider",
    "OAUTH_TOKEN_PATH",
    "PRICES_PATH",
    "PricesSmokeDiagnosticResult",
    "PricesSmokeResult",
    "ReadOnlySmokeResult",
    "STOCKS_PATH",
    "StockInfoSmokeDiagnosticResult",
    "StockInfoSmokeResult",
    "StockWarningsSmokeDiagnosticResult",
    "StockWarningsSmokeResult",
    "TokenProvider",
    "TossApiError",
    "TossApiClientContractPolicy",
    "TossApiContractValidationResult",
    "TossApiCredentialNamePolicy",
    "TossApiEndpointContract",
    "TossApiErrorContract",
    "TossApiExternalCapabilityFlags",
    "TossApiFakeFixture",
    "TossApiFakeRequest",
    "TossApiFakeResponse",
    "TossApiFakeTransportPolicy",
    "TossApiFakeTransportResult",
    "TossApiFakeTransportValidationResult",
    "TossApiRedactionPolicy",
    "TossApiRedactionResult",
    "TossApiRequestContract",
    "TossApiResponseContract",
    "TossAuthenticationError",
    "TossCandlesSmokeClient",
    "TossClientConfig",
    "TossClientConfigError",
    "TossClientFoundation",
    "TossMarketDataClient",
    "TossMarketInfoClient",
    "TossOAuthTokenProvider",
    "TossPricesSmokeClient",
    "TossReadOnlySmokeClient",
    "TossPermissionError",
    "TossRateLimitError",
    "TossServerError",
    "TossStockInfoClient",
    "TossStockInfoSmokeClient",
    "TossStockWarningsSmokeClient",
    "build_symbolic_toss_api_endpoint_contracts",
    "build_toss_api_client_contract_policy",
    "build_toss_api_credential_name_policy",
    "build_toss_api_error_contracts",
    "build_toss_api_external_capability_flags",
    "build_toss_api_fake_fixtures",
    "build_toss_api_fake_request",
    "build_toss_api_fake_transport_policy",
    "build_toss_api_redaction_policy",
    "build_toss_api_request_contract",
    "build_toss_api_response_contract",
    "extract_toss_result",
    "redact_mapping",
    "redact_sensitive_value",
    "raise_for_toss_status",
    "run_toss_api_client_contract_preflight_checks",
    "run_toss_api_fake_transport",
    "run_toss_api_fake_transport_preflight_checks",
    "validate_no_sensitive_output",
    "validate_toss_api_client_contract_policy",
    "validate_toss_api_endpoint_contract",
    "validate_toss_api_fake_fixture",
    "validate_toss_api_fake_transport_policy",
    "validate_toss_api_request_contract",
    "validate_toss_api_response_contract",
]
